export const experiences = [
    {
        role: "Lead Software Engineer",
        duration: "Jun 2026 - Present",
        link: "https://www.alkademy.com/",
        company: "@Alkademy ",
        location: 'https://flagcdn.com/w320/hu.png',
        summary: "Backend services across Alkademy's suite of products.",
        description1: "Design and build backend services for a multi-tenant journal platform, working with complex datasets and developing efficient data querying and processing workflows. Reduced API latency by roughly 35% through database and query optimisation, Redis caching, application-level improvements, and moving resource-intensive operations to background workers. Designed asynchronous job processing with BullMQ to keep heavy operations off the main request cycle, and integrated AWS S3 for secure file storage with signed URLs. Lead the breakdown and resolution of complex engineering problems across APIs, databases, and infrastructure, with system design decisions focused on performance, reliability, and scalability.",
        technologies: ["Typescript", "NestJs", "NodeJs", "Express", "Docker", "Redis", "BullMQ", "AWS", "S3", "Postgresql"],
    },
    {
        role: "Senior Software Engineer",
        duration: "Mar 2025 - May 2026",
        link: "https://www.mybeautybutler.com/",
        company: "@Beauty Butler ",
        location: 'https://flagcdn.com/w320/ng.png',
        summary: "Booking platform, concierge portal, and admin dashboard for beauty businesses.",
        description1: "Increased booking completion rates by roughly 25% by redesigning the end-to-end customer booking experience, simplifying scheduling workflows, and integrating real-time availability, payments, and location-based search across three production applications. Reduced average API response times by roughly 35% through database optimisation, Redis caching, and application performance tuning. Built and delivered the customer booking platform, concierge portal, and administrative dashboard, enabling 20+ partner businesses to manage bookings, customers, payments, and day-to-day operations through a unified platform. Architected scalable backend services for authentication, booking, scheduling, payments, notifications, and chat, and established reusable engineering patterns and code review practices that improved consistency across the team.",
        technologies: ["Typescript", "NextJs", "NestJs", "NodeJs", "Express", "Socket.io", "Docker", "Redis", "AWS", "MySQL"],
    },
    {
        role: "Frontend Engineer",
        duration: "Jun 2023 - Jan 2025",
        link: "https://clouddley.com/",
        company: "@Clouddley ",
        location: 'https://flagcdn.com/w320/us.png',
        summary: "Cloud management dashboards for provisioning apps, databases, and servers.",
        description1: "Reduced page load times by roughly 40% and improved Core Web Vitals through rendering optimisation, code splitting, lazy loading, and Lighthouse-driven performance tuning. Increased organic search visibility through technical SEO improvements, structured metadata, and accessibility enhancements across customer-facing products. Accelerated feature delivery by architecting reusable component libraries and shared hooks, reducing duplicate code across platform modules. Developed secure cloud management dashboards and authentication workflows that let developers provision and manage applications, databases, VPS instances, and AI workloads through a unified platform.",
        technologies: ["Typescript", "React", "NextJs", "NextAuth.js", "Zustand", "Tailwind", "React Query", "Vercel", "GitHub Actions"],
    },
    {
        role: "Frontend Engineer",
        badge: "Intern",
        duration: "Jan 2023 - Jun 2023",
        link: "https://minderacodeacademy.com/",
        company: "@Mindera ",
        location: 'https://flagcdn.com/w320/gb.png',
        summary: "Frontend engineering programme focused on React, Next.js, and TypeScript.",
        description1: "Completed an intensive frontend engineering programme focused on React, Next.js, TypeScript, modern JavaScript, and software architecture through hands-on project development. Led frontend development across collaborative team projects, translating product requirements into responsive, accessible, and maintainable user interfaces within Agile delivery cycles. Designed reusable React components and scalable frontend architecture, applying performance optimisation, debugging, and clean code principles through peer code reviews.",
        technologies: ["Typescript", "React", "NextJs", "Jest", "Zustand", "Javascript", "HTML5", "CSS", "Tailwind", "Git", "Figma"],
    },
    {
        role: "Backend Engineer",
        badge: "Intern",
        duration: "Jun 2021 - Jun 2022",
        link: "https://wildfire.ng/",
        company: "@WildFire ",
        location: 'https://flagcdn.com/w320/ng.png',
        summary: "Backend services and RESTful APIs with Node.js and Express.",
        description1: "Developed and maintained backend services and RESTful APIs using Node.js, Express.js, MySQL, and MongoDB, contributing to production web applications under the guidance of senior engineers. Implemented authentication, request validation, and business logic while improving API reliability and stability through debugging and code enhancements. Collaborated within Agile development teams, participating in code reviews, API testing, and Git-based workflows.",
        technologies: ["Javascript", "NodeJs", "Express", "MySQL", "MongoDB", "Git", "Postman"],
    },
];
