export const experiences = [
    {
        role: "Software Engineer",
        duration: "June 2026 - Present",
        link: "https://www.alkademy.com/",
        company: "@Alkademy ",
        location: 'https://flagcdn.com/w320/hu.png',
        description1: "Just getting started here. More to come.",
        technologies: ["React", "CSS", "Javascript", "Typescript", "Wordpress", "Tailwind", "NodeJs", "MongoDB", "SQL"],
    },
    {
        role: "Software Engineer",
        duration: "March 2025 - May 2026",
        link: "https://www.mybeautybutler.com/",
        company: "@Beauty Butler ",
        location: 'https://flagcdn.com/w320/ng.png',
        description1: "Built and optimised scalable REST APIs with Node.js, Express, and MySQL, cutting average response time by 40%, and implemented JWT authentication with robust error handling for secure, consistent client responses. Developed a real-time chat system using Socket.io, led a full Next.js admin dashboard rebuild with Zustand for global state, and refactored the frontend into reusable components — reducing duplication and improving maintainability. Collaborated with design to ship pixel-perfect UIs from Figma, optimised assets to WebP for Core Web Vitals gains, and worked cross-functionally across backend, frontend, and product to deliver a reliable, high-performance platform.",
        technologies: ["NextJs", "Typescript", "NodeJs", "NestJs", "MySQL", "Express", "AWS", "Devops", "Redis",],
    }, {
        role: "Frontend Engineer",
        duration: "June 2023 - Jan 2025",
        link: "https://clouddley.com/",
        company: "@Clouddley ",
        location: 'https://flagcdn.com/w320/us.png',
        description1: "Built and maintained high-performing web applications with Next.js, React, and TypeScript, refactoring legacy UI into reusable atomic components that cut code duplication and improved development speed by 40%. Implemented Google OAuth and GitHub auth via NextAuth.js, integrated backend APIs with complex client state management, and optimised performance through WebP conversion, video compression, and Next.js image optimisation. Improved SEO and accessibility with semantic HTML5, JSON-LD structured data, and ARIA standards — pushing Lighthouse scores to 95+.",
        technologies: ["NextJs", "Tailwind", "Typescript", 'Jest', "Zustand", "Framer Motion", "Custom Css",],
    },
    {
        role: "Frontend Engineer",
        badge: "Bootcamp",
        duration: "Jan 2023 - June 2023",
        link: "https://minderacodeacademy.com/",
        company: "@Mindera ",
        location: 'https://flagcdn.com/w320/gb.png',
        description1: "Built and shipped multiple Next.js and TypeScript projects under senior developer mentorship, applying modern React patterns, reusable component architecture, and clean coding standards. Worked closely with designers and engineers in Agile sprints to deliver accessible, responsive UIs with Tailwind CSS. Participated in code reviews, pair programming, and technical workshops — sharpening both my frontend skills and my ability to translate business requirements into polished user experiences.",
        technologies: ["NextJs", "Tailwind", "CSS", "Javascript", "Context Api", "SEO", "Agile Methodology"],
    },
    {
        role: "Backend Engineer",
        badge: "Intern",
        duration: "July 2021 - Dec 2021",
        link: "https://wildfire.ng/",
        company: "@WildFire ",
        location: 'https://flagcdn.com/w320/ng.png',
        description1: "Built and maintained RESTful APIs using Node.js, Express, and MongoDB under the guidance of senior engineers. Implemented new endpoints, improved error handling, and tested request cycles with Postman. Collaborated closely with the frontend team to ensure smooth API integration, while picking up Git workflows, code reviews, and Agile practices along the way.",
        technologies: ["Express", "NodeJs", "Javascript", "MongoDB", "REST"],
    },
];
