export const experiences = [
    {
        role: "Fullstack Engineer",
        duration: "Jan 2024 - Present",
        link: "https://appvarsity.vercel.app",
        company: "@Appvarsity ",
        location: 'https://flagcdn.com/w320/ng.png',
        description1: "I Founded and led the development of the platform to address personal challenges i faced as a student at Aptech, now serving 70+ students. Key responsibilities included leading a team of 4, assigning tasks, conducting code reviews, and presenting the platform to students. This experience enhanced my collaborative and leadership skills as I oversaw the frontend and backend integrations of the platform.",
        technologies: ["NextJs", "Tailwind", "Typescript", "Clerk", "Zustand", "Webhooks", "Sentry", "Git", "Mongodb", "Mongoose"],
    },
    {
        role: "Frontend Developer",
        duration: "April 2021 - Present",
        link: "https://clouddley.com/",
        company: "@Clouddley ",
        location: 'https://flagcdn.com/w320/us.png',
        description1: " I design intuitive user interfaces to enhance the platform's functionality and user experience. I focus on building responsive, performance-optimized designs while ensuring accessibility standards are met. I collaborate closely with cross-functional teams to integrate features seamlessly and maintain a cohesive product vision. My work involves leveraging modern technologies to deliver scalable solutions, improving customer satisfaction and usability.",
        technologies: ["NextJs", "Tailwind", "Typescript", 'Jest', "Zustand", "Framer Motion", "Custom Css",],
    },
    {
        role: "Frontend Developer Intern",
        duration: "Jan 2023 - July 2023",
        link: "https://minderacodeacademy.com/",
        company: "@Mindera ",
        location: 'https://flagcdn.com/w320/gb.png',
        description1: "I created responsive, accessible user interfaces optimized for performance. I embraced agile methodologies to improve teamwork and communication, fostering a more productive development process. As a team lead, I ensured projects were delivered on time by managing tasks and maintaining high-quality standards. This experience greatly enhanced my technical expertise, communication skills, and leadership abilities.",
        technologies: ["NextJs", "Tailwind", "CSS", "Javascript", "Context Api", "SEO", "Agile Methodology"],
    },
    {
        role: "Backend Engineer",
        duration: "Sept 2024 - Present",
        link: "https://aptech-nigeria.com/",
        company: "@Aptech ",
        location: 'https://flagcdn.com/w320/ng.png',
        description1: "I design and develop scalable and secure APIs, integrating seamlessly with MongoDB and PostgreSQL to support high-performance applications. I implement advanced API security measures, including throttling, rate limiting, and encrypted data handling, ensuring compliance with industry standards. I rigorously test and debug APIs, ensuring 99.9% uptime and consistent performance under high traffic conditions.",
        technologies: ["Rest APIs", "Express", "Nodejs", "OOP", "Postman", "Mongodb", "Postgresql", "Authentication • JWT ", "Git"],
    },
];
